#ifndef GENERATED_arrayNonRepeatSorted32760
#define GENERATED_arrayNonRepeatSorted32760
extern SingleTestContainer arrayNonRepeatSorted_NotAligned_32760_c;
extern SingleTestContainer arrayNonRepeatSorted_Aligned_32760_c;
#endif
