#ifndef GENERATED_arrayNonRepeat_REVERSE_Sorted32711
#define GENERATED_arrayNonRepeat_REVERSE_Sorted32711
extern SingleTestContainer arrayNonRepeat_REVERSE_Sorted_NotAligned_32711_c;
extern SingleTestContainer arrayNonRepeat_REVERSE_Sorted_Aligned_32711_c;
#endif
