#ifndef GENERATED_arrayNonRepeat_REVERSE_Sorted32717
#define GENERATED_arrayNonRepeat_REVERSE_Sorted32717
extern SingleTestContainer arrayNonRepeat_REVERSE_Sorted_NotAligned_32717_c;
extern SingleTestContainer arrayNonRepeat_REVERSE_Sorted_Aligned_32717_c;
#endif
