#ifndef GENERATED_arrayOne_EqualNumZeroes524288
#define GENERATED_arrayOne_EqualNumZeroes524288
extern SingleTestContainer arrayOne_EqualNumZeroes_NotAligned_524288_c;
extern SingleTestContainer arrayOne_EqualNumZeroes_Aligned_524288_c;
#endif
