#ifndef GENERATED_arrayOne_EqualNumZeroes2050
#define GENERATED_arrayOne_EqualNumZeroes2050
extern SingleTestContainer arrayOne_EqualNumZeroes_NotAligned_2050_c;
extern SingleTestContainer arrayOne_EqualNumZeroes_Aligned_2050_c;
#endif
