#ifndef GENERATED_arrayOne_EqualNumZeroes32
#define GENERATED_arrayOne_EqualNumZeroes32
extern SingleTestContainer arrayOne_EqualNumZeroes_NotAligned_32_c;
extern SingleTestContainer arrayOne_EqualNumZeroes_Aligned_32_c;
#endif
