#ifndef GENERATED_arrayOne_EqualNum1024
#define GENERATED_arrayOne_EqualNum1024
extern SingleTestContainer arrayOne_EqualNum_NotAligned_1024_c;
extern SingleTestContainer arrayOne_EqualNum_Aligned_1024_c;
#endif
