#ifndef GENERATED_arrayOne_EqualNum32756
#define GENERATED_arrayOne_EqualNum32756
extern SingleTestContainer arrayOne_EqualNum_NotAligned_32756_c;
extern SingleTestContainer arrayOne_EqualNum_Aligned_32756_c;
#endif
