#ifndef GENERATED_arrayRAND_Repeats64
#define GENERATED_arrayRAND_Repeats64
extern SingleTestContainer arrayRAND_Repeats_NotAligned_64_c;
extern SingleTestContainer arrayRAND_Repeats_Aligned_64_c;
#endif
