#ifndef GENERATED_arrayRAND_Repeats32756
#define GENERATED_arrayRAND_Repeats32756
extern SingleTestContainer arrayRAND_Repeats_NotAligned_32756_c;
extern SingleTestContainer arrayRAND_Repeats_Aligned_32756_c;
#endif
