#ifndef GENERATED_arrayOne_EqualNum32
#define GENERATED_arrayOne_EqualNum32
extern SingleTestContainer arrayOne_EqualNum_NotAligned_32_c;
extern SingleTestContainer arrayOne_EqualNum_Aligned_32_c;
#endif
