#ifndef GENERATED_arrayOne_EqualNum32724
#define GENERATED_arrayOne_EqualNum32724
extern SingleTestContainer arrayOne_EqualNum_NotAligned_32724_c;
extern SingleTestContainer arrayOne_EqualNum_Aligned_32724_c;
#endif
