#ifndef GENERATED_arrayOne_EqualNumZeroes37
#define GENERATED_arrayOne_EqualNumZeroes37
extern SingleTestContainer arrayOne_EqualNumZeroes_NotAligned_37_c;
extern SingleTestContainer arrayOne_EqualNumZeroes_Aligned_37_c;
#endif
