#ifndef GENERATED_arrayOne_EqualNumZeroes32711
#define GENERATED_arrayOne_EqualNumZeroes32711
extern SingleTestContainer arrayOne_EqualNumZeroes_NotAligned_32711_c;
extern SingleTestContainer arrayOne_EqualNumZeroes_Aligned_32711_c;
#endif
