#ifndef GENERATED_arrayOne_EqualNumZeroes256
#define GENERATED_arrayOne_EqualNumZeroes256
extern SingleTestContainer arrayOne_EqualNumZeroes_NotAligned_256_c;
extern SingleTestContainer arrayOne_EqualNumZeroes_Aligned_256_c;
#endif
