#ifndef GENERATED_arrayNonRepeat_Shuffled1024
#define GENERATED_arrayNonRepeat_Shuffled1024
extern SingleTestContainer arrayNonRepeat_Shuffled_NotAligned_1024_c;
extern SingleTestContainer arrayNonRepeat_Shuffled_Aligned_1024_c;
#endif
