#ifndef GENERATED_arrayNonRepeat_Shuffled32715
#define GENERATED_arrayNonRepeat_Shuffled32715
extern SingleTestContainer arrayNonRepeat_Shuffled_NotAligned_32715_c;
extern SingleTestContainer arrayNonRepeat_Shuffled_Aligned_32715_c;
#endif
