#ifndef GENERATED_arrayNonRepeatSorted_SomeZeroes32
#define GENERATED_arrayNonRepeatSorted_SomeZeroes32
extern SingleTestContainer arrayNonRepeatSorted_SomeZeroes_NotAligned_32_c;
extern SingleTestContainer arrayNonRepeatSorted_SomeZeroes_Aligned_32_c;
#endif
