#ifndef GENERATED_arrayNonRepeatSorted_SomeZeroes37
#define GENERATED_arrayNonRepeatSorted_SomeZeroes37
extern SingleTestContainer arrayNonRepeatSorted_SomeZeroes_NotAligned_37_c;
extern SingleTestContainer arrayNonRepeatSorted_SomeZeroes_Aligned_37_c;
#endif
