#ifndef GENERATED_arrayNonRepeat_REVERSE_Sorted32
#define GENERATED_arrayNonRepeat_REVERSE_Sorted32
extern SingleTestContainer arrayNonRepeat_REVERSE_Sorted_NotAligned_32_c;
extern SingleTestContainer arrayNonRepeat_REVERSE_Sorted_Aligned_32_c;
#endif
