#ifndef GENERATED_arrayRAND_Repeats32724
#define GENERATED_arrayRAND_Repeats32724
extern SingleTestContainer arrayRAND_Repeats_NotAligned_32724_c;
extern SingleTestContainer arrayRAND_Repeats_Aligned_32724_c;
#endif
