#ifndef GENERATED_arrayRAND_Repeats32
#define GENERATED_arrayRAND_Repeats32
extern SingleTestContainer arrayRAND_Repeats_NotAligned_32_c;
extern SingleTestContainer arrayRAND_Repeats_Aligned_32_c;
#endif
