#ifndef GENERATED_arrayNonRepeat_Shuffled32768
#define GENERATED_arrayNonRepeat_Shuffled32768
extern SingleTestContainer arrayNonRepeat_Shuffled_NotAligned_32768_c;
extern SingleTestContainer arrayNonRepeat_Shuffled_Aligned_32768_c;
#endif
