#ifndef GENERATED_arrayNonRepeat_Shuffled64
#define GENERATED_arrayNonRepeat_Shuffled64
extern SingleTestContainer arrayNonRepeat_Shuffled_NotAligned_64_c;
extern SingleTestContainer arrayNonRepeat_Shuffled_Aligned_64_c;
#endif
