#ifndef GENERATED_arrayNonRepeatSorted32710
#define GENERATED_arrayNonRepeatSorted32710
extern SingleTestContainer arrayNonRepeatSorted_NotAligned_32710_c;
extern SingleTestContainer arrayNonRepeatSorted_Aligned_32710_c;
#endif
