#ifndef GENERATED_arrayNonRepeatSorted32756
#define GENERATED_arrayNonRepeatSorted32756
extern SingleTestContainer arrayNonRepeatSorted_NotAligned_32756_c;
extern SingleTestContainer arrayNonRepeatSorted_Aligned_32756_c;
#endif
