#ifndef GENERATED_arrayNonRepeatSorted_SomeZeroes2049
#define GENERATED_arrayNonRepeatSorted_SomeZeroes2049
extern SingleTestContainer arrayNonRepeatSorted_SomeZeroes_NotAligned_2049_c;
extern SingleTestContainer arrayNonRepeatSorted_SomeZeroes_Aligned_2049_c;
#endif
