#ifndef GENERATED_arrayNonRepeatSorted_SomeZeroes32768
#define GENERATED_arrayNonRepeatSorted_SomeZeroes32768
extern SingleTestContainer arrayNonRepeatSorted_SomeZeroes_NotAligned_32768_c;
extern SingleTestContainer arrayNonRepeatSorted_SomeZeroes_Aligned_32768_c;
#endif
